apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpcapi-app-ingress
spec:
  rules:
    - host: gpcapi.kubernetes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gpcapi
                port:
                  number: 80
