networks:
  gpc-net:

volumes:
  gpc-vol:

services:
  gpc-reactjs:
    container_name: gpc-reactjs-dev
    build:
      context: ./react-js-client
      target: production
    ports:
      - 3000:3000
    networks:
      - gpc-net
    volumes:
      - type: volume
        source: gpc-vol
        target: /app

  gpcapi-dotnet:
    container_name: gpcapi
    build:
      context: ./gpcapi
    ports:
      - "8080:80"
    depends_on:
      - gpcdb
    networks:
      - gpc-net
    volumes:
      - type: volume
        source: gpc-vol
        target: /src

  gpcdb:
    container_name: gpcdb
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Password@8"
      ACCEPT_EULA: "Y"
    networks:
      gpc-net:
